Repository glandjs/gland, pull requests merged in 2025-03, with the labels that each got.

#75 Fix Event Processing Bug and Add Broker Method in HTTP-Core
  packages/events/broker.ts
  packages/events/container/node.ts
  packages/events/queue/circular-deque.ts
  packages/http/adapter/http.adapter.ts
  packages/http/http-core.ts
  packages/http/interface/http-context.interface.ts
Labels: bug

#77 feat(core): Unify event and routing systems with optimized radix tree implementation
  packages/common/index.ts
  packages/common/tree/index.ts
  packages/common/tree/node.ts
  packages/common/tree/path.utils.ts
  packages/common/tree/tree.ts
  packages/common/utils/index.ts
  packages/common/utils/vector.ts
  packages/events/broker.ts
  packages/events/container/bit-vector.ts
  packages/events/container/emitter.ts
  packages/events/container/index.ts
  packages/events/container/node.ts
  packages/events/container/queue-utils.ts
  packages/events/container/router.ts
  packages/events/queue/queue.ts
  packages/http/router/node/adder.ts
  packages/http/router/node/matcher.ts
  packages/http/router/node/node.ts
  packages/http/router/node/tree.ts
  packages/http/router/node/utils/index.ts
  packages/http/router/node/utils/path.util.ts
  packages/http/router/node/utils/segment-analyzer.util.ts
  packages/http/router/router.ts
Labels: enhancement

#83 feat(core): Add dependency-injection system & enhanced HTTP module with channel-based architecture
  packages/common/types/index.ts
  packages/core/application/application-initial.ts
  packages/core/application/index.ts
  packages/core/di/opaque-key-factory/index.ts
  packages/core/gland-factory.ts
  packages/core/injector/binder.ts
  packages/core/injector/container/container.ts
  packages/core/injector/container/index.ts
  packages/core/injector/container/module-container.ts
  packages/core/injector/discovery-service.ts
  packages/core/injector/explorer.ts
  packages/core/injector/graph.ts
  packages/core/injector/index.ts
  packages/core/injector/instance-wrapper.ts
  packages/core/injector/module.ts
  packages/core/injector/opaque-key-factory/deep-hashed-factory.ts
  packages/core/injector/opaque-key-factory/index.ts
  packages/core/injector/opaque-key-factory/module-opaque-key.interface.ts
  packages/core/injector/scanner/dependencies-scanner.ts
  packages/core/injector/scanner/index.ts
  packages/core/injector/scanner/metadata-scanner.ts
  packages/core/package.json
  packages/core/tsconfig.json
  packages/http/context/http-context.ts
  packages/http/http-core.ts
  packages/http/index.ts
  packages/http/types/app-options.types.ts
Labels: enhancement

#86 feat(core): Add dependency-injection system & enhanced HTTP module with channel-based architecture
  packages/common/types/index.ts
  packages/core/application/application-initial.ts
  packages/core/application/index.ts
  packages/core/di/opaque-key-factory/index.ts
  packages/core/gland-factory.ts
  packages/core/injector/binder.ts
  packages/core/injector/container/container.ts
  packages/core/injector/container/index.ts
  packages/core/injector/container/module-container.ts
  packages/core/injector/discovery-service.ts
  packages/core/injector/explorer.ts
  packages/core/injector/graph.ts
  packages/core/injector/index.ts
  packages/core/injector/instance-wrapper.ts
  packages/core/injector/module.ts
  packages/core/injector/opaque-key-factory/deep-hashed-factory.ts
  packages/core/injector/opaque-key-factory/index.ts
  packages/core/injector/opaque-key-factory/module-opaque-key.interface.ts
  packages/core/injector/scanner/dependencies-scanner.ts
  packages/core/injector/scanner/index.ts
  packages/core/injector/scanner/metadata-scanner.ts
  packages/core/package.json
  packages/core/tsconfig.json
  packages/http/context/http-context.ts
  packages/http/http-core.ts
  packages/http/index.ts
  packages/http/types/app-options.types.ts
Labels: enhancement

#89 feat(events, tests, ci, examples): Improve event handling, add tests & CI workflow
  .github/workflows/test.yml
  examples/very-simple.ts
  package.json
  packages/common/interfaces/events/event.interface.ts
  packages/common/tree/tree.ts
  packages/common/types/app.types.ts
  packages/common/types/decorators/index.ts
  packages/common/types/event.type.ts
  packages/common/types/events/index.ts
  packages/common/types/index.ts
  packages/common/types/modules.type.ts
  packages/common/utils/index.ts
  packages/common/utils/vector.ts
  packages/core/index.ts
  packages/core/injector/binder.ts
  packages/events/broker.ts
  packages/events/channel-proxy.ts
  packages/events/container/router.ts
  packages/events/queue/circular-deque.ts
  packages/events/queue/queue.ts
  packages/http/adapter/http-events.ts
  packages/http/config/config.container.ts
  packages/http/http-core.ts
  packages/http/index.ts
  packages/http/plugins/abstract-plugins.ts
  packages/http/plugins/channels/proxy.channel.ts
  test/integration/events/broker.spec.ts
  test/unit/events/circular-deque.spec.ts
  test/unit/events/queue.spec.ts
  test/unit/events/router.spec.ts
  tsconfig.json
Labels: bug, enhancement

#90 cd: fix run tests and add new script
  .github/workflows/test.yml
  package.json
Labels: bug

#93 chore: add simple changelog
  docs/CHANGELOG.md
Labels: enhancement
