Repository glandjs/gland, pull requests merged in 2025-04, with the labels that each got.

#96 fix(decorators): fix load reflect-metadata
  packages/common/decorators/core/index.ts
  packages/tsconfig.json
Labels: bug

#100 chore: add pnpm-lock.yaml in ignore file
  .prettierignore
  pnpm-lock.yaml
Labels: bug

#101 chore: Sponsors section removed and lighting and bitcoin addresses added. New svg image and new Lego created and replaced. Gland philosophy section updated.
  README.md
  docs/Logo.png
  docs/logo.svg
  packages/common/README.md
  packages/core/README.md
  packages/events/README.md
Labels: feature, documentation, refactor

#102 chore: update Philosophy for events and change donation title
  README.md
  packages/events/README.md
Labels: documentation, refactor

#105 add utils loadpackage and add link discord
  docs/CONTRIBUTING.md
  packages/common/README.md
  packages/common/utils/index.ts
  packages/common/utils/load-pkg.util.ts
  packages/core/README.md
  packages/core/adapter/adapter.abstract.ts
  packages/core/gland-factory.ts
  packages/events/README.md
Labels: feature, refactor

#106 chore: add coomment and release v1 alpha version
  .npmignore
  examples/very-simple.ts
  package.json
  packages/common/index.ts
  packages/common/package.json
  packages/core/index.ts
  packages/core/package.json
  packages/events/index.ts
  packages/events/package.json
  pnpm-lock.yaml
Labels: documentation

#109 feat(core): introduce saga-based module execution and NestJS-compatible dynamic module support
  examples/very-simple.ts
  packages/common/constant.ts
  packages/common/decorators/events/channel.decorator.ts
  packages/common/decorators/events/emit.decorator.ts
  packages/common/decorators/events/index.ts
  packages/common/decorators/events/saga/compensate.decorator.ts
  packages/common/decorators/events/saga/index.ts
  packages/common/decorators/events/saga/saga.decorator.ts
  packages/common/decorators/events/saga/step.decorator.ts
  packages/common/interfaces/events/channel.interface.ts
  packages/common/interfaces/events/index.ts
  packages/common/interfaces/modules.interfaces.ts
  packages/common/types/modules.type.ts
Labels: feature, documentation, refactor
